// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registry.Repository;

#nullable disable

namespace Registry.Migrations
{
    [DbContext(typeof(TradesManDbContext))]
    [Migration("20250602202857_AddedTradesmanImages")]
    partial class AddedTradesmanImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Registry.Models.ClientJobRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InitiatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobApprovedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShowToEveryone")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("JobApprovedId")
                        .IsUnique()
                        .HasFilter("[JobApprovedId] IS NOT NULL");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("Registry.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Declined")
                        .HasColumnType("bit");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TradesManId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TradesManId");

                    b.HasIndex("RequestId", "TradesManId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Registry.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TradesManJobResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TradesManJobResponseId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Registry.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Seen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("FromId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Registry.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Registry.Models.Speciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Registry.Models.TradesMan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradesMan");
                });

            modelBuilder.Entity("Registry.Models.TradesManImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TradesmanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TradesmanId");

                    b.ToTable("TradesManImages");
                });

            modelBuilder.Entity("Registry.Models.TradesManJobResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AproximationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Seen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WorkmanshipAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("TradesManJobResponses");
                });

            modelBuilder.Entity("Registry.Models.TradesManSpecialities", b =>
                {
                    b.Property<Guid>("TradesManId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecialityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TradesManId", "SpecialityId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("TradesManSpecialities");
                });

            modelBuilder.Entity("Registry.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Registry.Models.ClientJobRequest", b =>
                {
                    b.HasOne("Registry.Models.User", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Registry.Models.Job", "JobApproved")
                        .WithOne()
                        .HasForeignKey("Registry.Models.ClientJobRequest", "JobApprovedId");

                    b.Navigation("InitiatedBy");

                    b.Navigation("JobApproved");
                });

            modelBuilder.Entity("Registry.Models.Conversation", b =>
                {
                    b.HasOne("Registry.Models.ClientJobRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Registry.Models.User", "TradesMan")
                        .WithMany()
                        .HasForeignKey("TradesManId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("TradesMan");
                });

            modelBuilder.Entity("Registry.Models.Job", b =>
                {
                    b.HasOne("Registry.Models.TradesManJobResponse", "TradesManJobResponse")
                        .WithOne()
                        .HasForeignKey("Registry.Models.Job", "TradesManJobResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TradesManJobResponse");
                });

            modelBuilder.Entity("Registry.Models.Message", b =>
                {
                    b.HasOne("Registry.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registry.Models.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("From");
                });

            modelBuilder.Entity("Registry.Models.Review", b =>
                {
                    b.HasOne("Registry.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Registry.Models.TradesMan", b =>
                {
                    b.HasOne("Registry.Models.User", null)
                        .WithOne("TradesManProfile")
                        .HasForeignKey("Registry.Models.TradesMan", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Registry.Models.TradesManImages", b =>
                {
                    b.HasOne("Registry.Models.TradesMan", "TradesMan")
                        .WithMany("Images")
                        .HasForeignKey("TradesmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradesMan");
                });

            modelBuilder.Entity("Registry.Models.TradesManJobResponse", b =>
                {
                    b.HasOne("Registry.Models.Conversation", "Conversation")
                        .WithMany("Responses")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Registry.Models.TradesManSpecialities", b =>
                {
                    b.HasOne("Registry.Models.Speciality", "Speciality")
                        .WithMany("TradesMenSpecialities")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registry.Models.TradesMan", "TradesMan")
                        .WithMany("Specialities")
                        .HasForeignKey("TradesManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("TradesMan");
                });

            modelBuilder.Entity("Registry.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Registry.Models.Speciality", b =>
                {
                    b.Navigation("TradesMenSpecialities");
                });

            modelBuilder.Entity("Registry.Models.TradesMan", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("Registry.Models.User", b =>
                {
                    b.Navigation("TradesManProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
